# source 'http://rubygems.org'

# # gem 'sinatra'
# # gem 'activerecord', '~> 4.2', '>= 4.2.6', :require => 'active_record'
# # gem 'sinatra-activerecord', :require => 'sinatra/activerecord'
# # gem 'rake'
# # gem 'require_all'
# # gem 'sqlite3', '~> 1.3.6'
# # gem 'thin'
# # gem 'shotgun'
# # gem 'pry'
# # gem 'bcrypt'
# # gem 'tux'



# gem "sinatra", "~> 2.1"

# gem "activerecord", "~> 6.1"

# gem 'sinatra-activerecord'
 
# gem "rake", "~> 13.0"      #for console commands

# gem "require_all", "~> 3.0"

# gem "sqlite3", "~> 1.4"

# gem "thin", "~> 1.8"     #for server

# gem "shotgun", "~> 0.9.2"

# gem "pry", "~> 0.14.0"

# gem "bcrypt", "~> 3.1"     #for securing our password

# gem "tux", "~> 0.3.0"     #is giving us a sandbox to work and play with our objects like rake console

# frozen_string_literal: true

# source "https://rubygems.org"

# git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# # gem "rails"

# gem "sqlite3", "~> 1.4"

# gem "activerecord", "~> 6.1"

# gem "rake", "~> 13.0"

# gem "pry", "~> 0.14.0"

# gem "sinatra-activerecord", "~> 2.0"

# gem "require_all", "~> 3.0"

# gem "shotgun", "~> 0.9.2"

# gem "sinatra", "~> 2.1"

# gem "bcrypt", "~> 3.1"

# gem "dotenv", "~> 2.7"

source "https://rubygems.org"

gem 'pry'
gem 'sqlite3'
gem 'rake'
gem 'activerecord'
gem 'sinatra-activerecord'

gem 'sinatra'
gem 'rack'

gem 'require_all'
gem "thin", "~> 1.8"

gem "tux"

gem "shotgun", "~> 0.9.2"

gem "bcrypt", "~> 3.1"

gem "dotenv", "~> 2.7"
